### ISSUE TITLE
Turn this into a middleware or store enhancer?

### ISSUE THREAD

**Issue by markerikson** [benjaminhadfield/redux-data-dispatch#1]
The setup/config process for this lib seems confusing.  It looks like it would be better suited to be a middleware or store enhancer instead.

**Comment by benmoose** [comment]
@markerikson Yeah great idea I totally agree. This lib was thrown together in a few hours to there's definitely loads of restructuring to do

Feel free to send over an implementation using middleware, otherwise I'll start working on this next week :)

**Comment by markerikson** [comment]
Looking at the middleware signature, I'm not sure this is going to play well with the rest of the ecosystem.  `dispatch` is defined as taking a single parameter, `action`, and so middleware normally just pass along that one parameter via `next(action)`.  If your middleware is expecting two parameters, having any other middleware in front of this one (like, say, `redux-thunk`) will mean that your middleware will never see the second parameter.

I'd suggest adding the owner/dependencies data to the action itself.  The Flux Standard Action `meta` field would be a good choice here.

**Comment by benmoose** [comment]
Ahh that explains the weird bugs I've been getting :P Thanks a lot! (again)
